package com.jsanfil.photoshare.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PhotoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public PhotoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOriginalPathIsNull() {
            addCriterion("originalPath is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPathIsNotNull() {
            addCriterion("originalPath is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPathEqualTo(String value) {
            addCriterion("originalPath =", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathNotEqualTo(String value) {
            addCriterion("originalPath <>", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathGreaterThan(String value) {
            addCriterion("originalPath >", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathGreaterThanOrEqualTo(String value) {
            addCriterion("originalPath >=", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathLessThan(String value) {
            addCriterion("originalPath <", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathLessThanOrEqualTo(String value) {
            addCriterion("originalPath <=", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathLike(String value) {
            addCriterion("originalPath like", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathNotLike(String value) {
            addCriterion("originalPath not like", value, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathIn(List<String> values) {
            addCriterion("originalPath in", values, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathNotIn(List<String> values) {
            addCriterion("originalPath not in", values, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathBetween(String value1, String value2) {
            addCriterion("originalPath between", value1, value2, "originalPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPathNotBetween(String value1, String value2) {
            addCriterion("originalPath not between", value1, value2, "originalPath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathIsNull() {
            addCriterion("websizePath is null");
            return (Criteria) this;
        }

        public Criteria andWebsizePathIsNotNull() {
            addCriterion("websizePath is not null");
            return (Criteria) this;
        }

        public Criteria andWebsizePathEqualTo(String value) {
            addCriterion("websizePath =", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathNotEqualTo(String value) {
            addCriterion("websizePath <>", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathGreaterThan(String value) {
            addCriterion("websizePath >", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathGreaterThanOrEqualTo(String value) {
            addCriterion("websizePath >=", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathLessThan(String value) {
            addCriterion("websizePath <", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathLessThanOrEqualTo(String value) {
            addCriterion("websizePath <=", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathLike(String value) {
            addCriterion("websizePath like", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathNotLike(String value) {
            addCriterion("websizePath not like", value, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathIn(List<String> values) {
            addCriterion("websizePath in", values, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathNotIn(List<String> values) {
            addCriterion("websizePath not in", values, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathBetween(String value1, String value2) {
            addCriterion("websizePath between", value1, value2, "websizePath");
            return (Criteria) this;
        }

        public Criteria andWebsizePathNotBetween(String value1, String value2) {
            addCriterion("websizePath not between", value1, value2, "websizePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathIsNull() {
            addCriterion("thumbnailPath is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathIsNotNull() {
            addCriterion("thumbnailPath is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathEqualTo(String value) {
            addCriterion("thumbnailPath =", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathNotEqualTo(String value) {
            addCriterion("thumbnailPath <>", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathGreaterThan(String value) {
            addCriterion("thumbnailPath >", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnailPath >=", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathLessThan(String value) {
            addCriterion("thumbnailPath <", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathLessThanOrEqualTo(String value) {
            addCriterion("thumbnailPath <=", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathLike(String value) {
            addCriterion("thumbnailPath like", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathNotLike(String value) {
            addCriterion("thumbnailPath not like", value, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathIn(List<String> values) {
            addCriterion("thumbnailPath in", values, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathNotIn(List<String> values) {
            addCriterion("thumbnailPath not in", values, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathBetween(String value1, String value2) {
            addCriterion("thumbnailPath between", value1, value2, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andThumbnailPathNotBetween(String value1, String value2) {
            addCriterion("thumbnailPath not between", value1, value2, "thumbnailPath");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andFormattedDateIsNull() {
            addCriterion("formattedDate is null");
            return (Criteria) this;
        }

        public Criteria andFormattedDateIsNotNull() {
            addCriterion("formattedDate is not null");
            return (Criteria) this;
        }

        public Criteria andFormattedDateEqualTo(String value) {
            addCriterion("formattedDate =", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateNotEqualTo(String value) {
            addCriterion("formattedDate <>", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateGreaterThan(String value) {
            addCriterion("formattedDate >", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateGreaterThanOrEqualTo(String value) {
            addCriterion("formattedDate >=", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateLessThan(String value) {
            addCriterion("formattedDate <", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateLessThanOrEqualTo(String value) {
            addCriterion("formattedDate <=", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateLike(String value) {
            addCriterion("formattedDate like", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateNotLike(String value) {
            addCriterion("formattedDate not like", value, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateIn(List<String> values) {
            addCriterion("formattedDate in", values, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateNotIn(List<String> values) {
            addCriterion("formattedDate not in", values, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateBetween(String value1, String value2) {
            addCriterion("formattedDate between", value1, value2, "formattedDate");
            return (Criteria) this;
        }

        public Criteria andFormattedDateNotBetween(String value1, String value2) {
            addCriterion("formattedDate not between", value1, value2, "formattedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photos
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 04 21:39:42 PDT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photos
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}