package com.jsanfil.photoshare.model;

import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class Photo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.id
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.originalPath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String originalPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.websizePath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String websizePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.thumbnailPath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String thumbnailPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.title
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.subject
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.description
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.date
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.formattedDate
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    private String formattedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.id
     *
     * @return the value of photos.id
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.id
     *
     * @param id the value for photos.id
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.originalPath
     *
     * @return the value of photos.originalPath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getOriginalPath() {
        return originalPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.originalPath
     *
     * @param originalPath the value for photos.originalPath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setOriginalPath(String originalPath) {
        this.originalPath = originalPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.websizePath
     *
     * @return the value of photos.websizePath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getWebsizePath() {
        return websizePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.websizePath
     *
     * @param websizePath the value for photos.websizePath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setWebsizePath(String websizePath) {
        this.websizePath = websizePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.thumbnailPath
     *
     * @return the value of photos.thumbnailPath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getThumbnailPath() {
        return thumbnailPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.thumbnailPath
     *
     * @param thumbnailPath the value for photos.thumbnailPath
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setThumbnailPath(String thumbnailPath) {
        this.thumbnailPath = thumbnailPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.title
     *
     * @return the value of photos.title
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.title
     *
     * @param title the value for photos.title
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.subject
     *
     * @return the value of photos.subject
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.subject
     *
     * @param subject the value for photos.subject
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.description
     *
     * @return the value of photos.description
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.description
     *
     * @param description the value for photos.description
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.date
     *
     * @return the value of photos.date
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.date
     *
     * @param date the value for photos.date
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.formattedDate
     *
     * @return the value of photos.formattedDate
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public String getFormattedDate() {
        return formattedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.formattedDate
     *
     * @param formattedDate the value for photos.formattedDate
     *
     * @mbggenerated Thu Oct 04 21:39:42 PDT 2012
     */
    public void setFormattedDate(String formattedDate) {
        this.formattedDate = formattedDate;
    }
}